services:
  api:
    image: ghcr.io/coollabsio/next-image-transformation
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - ALLOWED_REMOTE_DOMAINS=*
      - IMGPROXY_URL=http://imgproxy:8080
    healthcheck:
      test: "wget -qO- http://localhost:3000/health || exit 1"
      interval: 2s
      timeout: 10s
      retries: 5
    depends_on:
      imgproxy:
        condition: service_healthy
  imgproxy:
    image: darthsim/imgproxy
    environment:
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_USE_ETAG=true
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      interval: 2s
      timeout: 10s
      retries: 5
